vcom ../vhdl/clkPrescale_.vhd
vcom ../vhdl/clkPrescale_rtl.vhd
vcom ../vhdl/clkPrescale_rtl_cfg.vhd
vcom ../vhdl/mux4to1_.vhd
vcom ../vhdl/mux4to1_rtl.vhd
vcom ../vhdl/mux4to1_rtl_cfg.vhd
vcom ../vhdl/counter_fsm_.vhd
vcom ../vhdl/counter_fsm_rtl.vhd
vcom ../vhdl/counter_fsm_rtl_cfg.vhd
vcom ../vhdl/io_ctrl_.vhd
vcom ../vhdl/io_ctrl_rtl.vhd
vcom ../vhdl/io_ctrl_rtl_cfg.vhd
vcom ../vhdl/CounterTop_.vhd
vcom ../vhdl/CounterTop_struc.vhd
vcom ../vhdl/CounterTop_struc_cfg.vhd
vcom ../tb/tb_CounterTop_.vhd
vcom ../tb/tb_CounterTop_sim.vhd
vcom ../tb/tb_CounterTop_sim_cfg.vhd