vcom ../vhdl/ioCtrl_.vhd
vcom ../vhdl/ioCtrl_rtl.vhd
vcom ../vhdl/ioCtrl_rtl_cfg.vhd
vcom ../vhdl/clkPrescale_.vhd
vcom ../vhdl/clkPrescale_rtl.vhd
vcom ../vhdl/clkPrescale_rtl_cfg.vhd
vcom ../vhdl/mux4to1_.vhd
vcom ../vhdl/mux4to1_rtl.vhd
vcom ../vhdl/mux4to1_rtl_cfg.vhd
vcom ../tb/tb_ioCtrl_.vhd
vcom ../tb/tb_ioCtrl_sim.vhd
vcom ../tb/tb_ioCtrl_sim_cfg.vhd
